# Generated by Django 4.2.2 on 2023-07-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AggregatedPredictions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_id", models.BigIntegerField()),
                ("day", models.BigIntegerField()),
                ("month", models.BigIntegerField()),
                ("average_prediction", models.BigIntegerField()),
            ],
            options={
                "db_table": "aggregated_predictions",
            },
        ),
        migrations.CreateModel(
            name="Cafe",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("rating", models.DecimalField(decimal_places=1, max_digits=3)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("image_url", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "cafe",
            },
        ),
        migrations.CreateModel(
            name="Predictions",
            fields=[
                (
                    "location_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("hour", models.BigIntegerField()),
                ("day", models.BigIntegerField()),
                ("month", models.BigIntegerField()),
                ("week_of_year", models.BigIntegerField()),
                ("prediction", models.BigIntegerField(null=True)),
                ("datetime", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "predictions",
            },
        ),
    ]
