# Generated by Django 4.2.3 on 2023-07-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'cafe',
            },
        ),
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('location_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('hour', models.BigIntegerField()),
                ('day', models.BigIntegerField()),
                ('month', models.BigIntegerField()),
                ('week_of_month', models.BigIntegerField()),
                ('normalised_prediction', models.FloatField()),
            ],
            options={
                'db_table': 'predictions',
            },
        ),
    ]
