# Generated by Django 4.2.3 on 2023-07-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yelp_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedpredictions',
            name='week_of_year',
            field=models.BigIntegerField(null=True),
        ),
    ]
