# Generated by Django 4.2.3 on 2023-07-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yelp_api', '0002_aggregatedpredictions_week_of_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPredictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.BigIntegerField()),
                ('month', models.BigIntegerField()),
                ('week_of_year', models.BigIntegerField(null=True)),
                ('monthly_prediction', models.BigIntegerField()),
            ],
            options={
                'db_table': 'monthly_predictions',
            },
        ),
    ]
