# Generated by Django 4.2.3 on 2023-07-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yelp_api', '0003_monthlypredictions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlypredictions',
            name='week_of_year',
        ),
    ]
