# Generated by Django 4.2.3 on 2023-08-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yelp_api', '0006_restaurants_alter_bars_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
