# Generated by Django 4.2.2 on 2023-07-03 15:01

from django.db import migrations, models

# Django migration file
# Automaticlaly generated when you run the makemigration command
# The migration file contains instructions on how to modify the database schema to reflect changes in your models.


# define migration class
class Migration(migrations.Migration):

    # indicates this is the initial migration of the app
    initial = True

    # indicates any dependencies this migration has on other migrations
    dependencies = []

    # list of migration operations that will be applied to the database, here there is just one
    operations = [
        migrations.CreateModel(
            name="Cafe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("rating", models.DecimalField(decimal_places=1, max_digits=3)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
    ]

# Will result in database schema being modified to include a new table called Cafe with specified fields