# Generated by Django 4.2.2 on 2023-07-03 15:41

from django.db import migrations

# Django migrations file

class Migration(migrations.Migration):


    # Depdency on previous migration with name 0001_initial.py from the yelp_api app
    # Operations attribute is a list of migration operations will be applied to the database

    # In this case the migrations.DeleteModel operation is used to delete a model from the database

    dependencies = [
        ("yelp_api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cafe",
        ),
    ]

# By running this migration, the database schema will be modified to delete the "Cafe" model and its associated table from the database.