# Generated by Django 4.2.3 on 2023-07-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yelp_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
