# Generated by Django 4.2.2 on 2023-07-03 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yelp_api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cafe",
        ),
    ]
