# Generated by Django 4.2.2 on 2023-07-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yelp_api", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="cafe_id",
            field=models.FloatField(default=0.0),
        ),
    ]
