# Generated by Django 4.2.2 on 2023-07-10 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yelp_api", "0004_remove_cafe_id_cafe_idl"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cafe",
            old_name="idl",
            new_name="id",
        ),
    ]
