# Generated by Django 4.2.2 on 2023-07-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yelp_api", "0004_cafe_cafe_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cafe",
            name="cafe_id",
        ),
        migrations.AlterField(
            model_name="cafe",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
