# Generated by Django 4.2.2 on 2023-07-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yelp_api", "0005_remove_cafe_cafe_id_alter_cafe_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="image_url",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
